port: 8080
drivers:
  - name: clickhouse
    main_storage: true
    options:
      - 'minActiveConn=0'
      - 'maxActiveConn=1'
      - 'maxInActiveTime=300000'
      - 'address=clickhouse:9000'
  - name: file
    options:
      - 'option=value'
