port: 8080
drivers:
  - name: clickhouse
    main_storage: true
    options:
      - 'dsnopts=database=hermes'
      - 'dsnopts=debug=false'
      - 'minActiveConn=20'
      - 'maxActiveConn=100'
      - 'maxInActiveTime=300000'
      - 'address=localhost:9000'
#  - name: file
#    options:
#      - 'option=value'
